# Intro
This Notebook is to aggretate the dataset that is extract feature from finbert and LLM.

# News Data

## Data import

In [37]:
import pandas as pd

news_df = pd.read_csv('finbert_llm_sentiment_inserted.csv')

print(news_df.shape)
display(news_df.head())
news_df

/var/folders/s2/gqpw_6dd5n7b8c1hzy_q5s0w0000gn/T/ipykernel_11981/2232204447.py:3: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  news_df = pd.read_csv('finbert_llm_sentiment_inserted.csv')

(451165, 11)

,date,headline,sentiment_score_finbert,sentiment_positive_finbert,sentiment_neutral_finbert,sentiment_negative_finbert,sentiment_score,relevance_score,event_importance,event_type,sentiment_score_llm
0,2006-11-13 03:16:00-05:00,"Hitachi, GE boost alliance in nuclear power bu...",0.284925,0.826591,0.162399,0.011009,NaN,0.4,0.3,merger,0.2
1,2006-11-13 08:45:00-05:00,"Volvo to cut 1,000 staff at Virginia plant",-0.348377,0.007027,0.025183,0.967790,NaN,0.4,0.3,supply-chain,-0.6
2,2006-11-13 03:15:00-05:00,European banks hiding full pension obligations,0.003950,0.039472,0.938750,0.021779,NaN,0.6,0.5,regulatory,-0.4
3,2006-11-13 07:13:00-05:00,"Hitachi, GE to form joint nuclear power ventures",0.010726,0.059743,0.928143,0.012114,NaN,0.6,0.4,merger,0.2
4,2006-11-13 07:29:00-05:00,Eddie Bauer agrees to be bought for $286 million,0.035885,0.156745,0.834435,0.008820,NaN,0.4,0.3,merger,0.2

,date,headline,sentiment_score_finbert,sentiment_positive_finbert,sentiment_neutral_finbert,sentiment_negative_finbert,sentiment_score,relevance_score,event_importance,event_type,sentiment_score_llm
0,2006-11-13 03:16:00-05:00,"Hitachi, GE boost alliance in nuclear power bu...",0.284925,0.826591,0.162399,0.011009,NaN,0.4,0.3,merger,0.2
1,2006-11-13 08:45:00-05:00,"Volvo to cut 1,000 staff at Virginia plant",-0.348377,0.007027,0.025183,0.967790,NaN,0.4,0.3,supply-chain,-0.6
2,2006-11-13 03:15:00-05:00,European banks hiding full pension obligations,0.003950,0.039472,0.938750,0.021779,NaN,0.6,0.5,regulatory,-0.4
3,2006-11-13 07:13:00-05:00,"Hitachi, GE to form joint nuclear power ventures",0.010726,0.059743,0.928143,0.012114,NaN,0.6,0.4,merger,0.2
4,2006-11-13 07:29:00-05:00,Eddie Bauer agrees to be bought for $286 million,0.035885,0.156745,0.834435,0.008820,NaN,0.4,0.3,merger,0.2
...,...,...,...,...,...,...,...,...,...,...,...
451160,2011-04-19 04:01:00-04:00,Houston Rockets Won’t Retain Rick Adelman as C...,-0.028285,0.024732,0.833995,0.141273,NaN,NaN,NaN,NaN,NaN
451161,2011-04-19 15:35:14-04:00,Colombian Peso Advances to Six-Month High on H...,0.327533,0.933918,0.032656,0.033426,NaN,NaN,NaN,NaN,NaN
451162,2011-04-19 01:42:12-04:00,Apple Said to Add Foxconn’s Chimei as Supplier...,0.085871,0.322494,0.669837,0.007669,NaN,NaN,NaN,NaN,NaN
451163,2011-04-19 06:25:34-04:00,"CEZ, Bank Pekao Shares May Move: Central Europ...",-0.026311,0.035378,0.821849,0.142773,NaN,NaN,NaN,NaN,NaN
451164,2011-04-19 04:30:00-04:00,"Popolare di Milano May Join Intesa, Paschi in ...",0.009950,0.055641,0.933085,0.011274,NaN,NaN,NaN,NaN,NaN

## Remove non model input features
For better performance in weak computer(small amount of ram)

In [38]:
news_df = news_df.drop(columns=['headline'])
display(news_df.head())

,date,sentiment_score_finbert,sentiment_positive_finbert,sentiment_neutral_finbert,sentiment_negative_finbert,sentiment_score,relevance_score,event_importance,event_type,sentiment_score_llm
0,2006-11-13 03:16:00-05:00,0.284925,0.826591,0.162399,0.011009,NaN,0.4,0.3,merger,0.2
1,2006-11-13 08:45:00-05:00,-0.348377,0.007027,0.025183,0.967790,NaN,0.4,0.3,supply-chain,-0.6
2,2006-11-13 03:15:00-05:00,0.003950,0.039472,0.938750,0.021779,NaN,0.6,0.5,regulatory,-0.4
3,2006-11-13 07:13:00-05:00,0.010726,0.059743,0.928143,0.012114,NaN,0.6,0.4,merger,0.2
4,2006-11-13 07:29:00-05:00,0.035885,0.156745,0.834435,0.008820,NaN,0.4,0.3,merger,0.2

## Sort by Date

In [39]:
# sort by date
news_df = news_df.sort_values('date')
display(news_df.head())

,date,sentiment_score_finbert,sentiment_positive_finbert,sentiment_neutral_finbert,sentiment_negative_finbert,sentiment_score,relevance_score,event_importance,event_type,sentiment_score_llm
59458,2006-10-20 20:16:16-04:00,0.312001,0.914320,0.022552,0.063128,NaN,NaN,NaN,NaN,NaN
30003,2006-10-21 00:08:44-04:00,0.000008,0.026059,0.947917,0.026024,NaN,0.6,0.3,analyst,0.2
269287,2006-10-23 11:51:36-04:00,0.051074,0.235344,0.723311,0.041345,NaN,NaN,NaN,NaN,NaN
269286,2006-10-23 20:00:29-04:00,-0.269634,0.041104,0.151949,0.806947,NaN,NaN,NaN,NaN,NaN
264729,2006-10-24 01:32:04-04:00,0.006762,0.046718,0.936810,0.016472,NaN,NaN,NaN,NaN,NaN

# Price data

## yFinance library

In [40]:
import yfinance as yf

def download_finance_data(
    symbol: str,
    start_date: str,
    end_date: str,
    interval: str = '1d'
) -> pd.DataFrame:
    """Download financial data from Yahoo Finance.
    
    Args:
        symbol (str): Stock symbol (e.g., '^SPX')
        start_date (str): Start date in 'YYYY-MM-DD' format
        end_date (str): End date in 'YYYY-MM-DD' format
        interval (str): Data interval ('1d' for daily, '1h' for hourly, etc.)
    
    Returns:
        pd.DataFrame: The downloaded data
    """
    # Download data from Yahoo Finance
    print(f"Downloading {interval} data for {symbol}...")
    ticker = yf.Ticker(symbol)
    df = ticker.history(start=start_date, end=end_date, interval=interval)
    
    # Reset index to make Date a column
    df = df.reset_index()
    
    # Print data information
    print(f"\nData shape: {df.shape}")
    print("Columns in the dataset:")
    print(df.columns.tolist())
    
    return df

## Download the price data by the date range of the news data

In [41]:
# Convert date column to datetime first
news_df['date'] = pd.to_datetime(news_df['date'])

# Get the min and max dates from news_df (day only)
start_date = news_df['date'].min().strftime('%Y-%m-%d')
end_date = news_df['date'].max().strftime('%Y-%m-%d')

print(f"Date range: {start_date} to {end_date}")

Date range: 2006-10-20 to 2013-11-26

/var/folders/s2/gqpw_6dd5n7b8c1hzy_q5s0w0000gn/T/ipykernel_11981/1276877657.py:2: FutureWarning: In a future version of pandas, parsing datetimes with mixed time zones will raise an error unless `utc=True`. Please specify `utc=True` to opt in to the new behaviour and silence this warning. To create a `Series` with mixed offsets and `object` dtype, please use `apply` and `datetime.datetime.strptime`
  news_df['date'] = pd.to_datetime(news_df['date'])

In [42]:
# Download S&P 500 data for the date range
spx_df = None
try:
    spx_df = download_finance_data(
        symbol='^SPX',
        start_date=start_date,
        end_date=end_date,
        interval='1d'
    )
    # Display first few rows
    print("\nFirst few rows of S&P 500 data:")
    print(spx_df.head())
except Exception as e:
    print(f"Error downloading data: {e}")
    pass

Downloading 1d data for ^SPX...
Error downloading data: Too Many Requests. Rate limited. Try after a while.

Note: When working with yFinance API, you may encounter common issues such as rate limiting or discontinued symbols. 
These are typical challenges when working with financial data APIs. If you experience these issues:
1. First try updating to the latest version of yFinance using: pip install --upgrade yfinance
2. If problems persist, you can manually download the data from Yahoo Finance and import it using the code below

In [43]:
if spx_df is None:
    spx_df = pd.read_csv('SPX_1d.csv')
spx_df.head()

,Date,Open,High,Low,Close,Volume
0,2006-10-20 00:00:00-04:00,1366.939941,1368.660034,1362.099976,1368.599976,2526410000
1,2006-10-23 00:00:00-04:00,1368.579956,1377.400024,1363.939941,1377.020020,2480430000
2,2006-10-24 00:00:00-04:00,1377.020020,1377.780029,1372.420044,1377.380005,2876890000
3,2006-10-25 00:00:00-04:00,1377.359985,1383.609985,1376.000000,1382.219971,2953540000
4,2006-10-26 00:00:00-04:00,1382.209961,1389.449951,1379.469971,1389.079956,2793350000

## Insert Technical Indicators

In [44]:
import pandas as pd
import numpy as np
from ta import add_all_ta_features
from ta.trend import SMAIndicator, EMAIndicator, MACD
from ta.momentum import RSIIndicator, StochasticOscillator
from ta.volatility import BollingerBands, AverageTrueRange
from ta.volume import OnBalanceVolumeIndicator, MFIIndicator
from ta.trend import CCIIndicator
from typing import List, Dict

def calculate_technical_indicators(df: pd.DataFrame, indicators: List[Dict]) -> pd.DataFrame:
    """
    Calculate technical indicators for the given price data using ta library.
    
    Args:
        df (pd.DataFrame): Price data with OHLCV columns
        indicators (List[Dict]): List of indicator configurations
            Each dict should have:
            - name: str, name of the indicator
            - window: int (optional), window size for the indicator
            
    Returns:
        pd.DataFrame: DataFrame with calculated indicators
        
    Example:
        indicators = [
            {'name': 'bb', 'window': 20},
            {'name': 'rsi', 'window': 14}
        ]
        df_with_indicators = calculate_technical_indicators(price_df, indicators)
    """
    if df is None:
        raise ValueError("DataFrame is not initialized")
    
    for indicator in indicators:
        name = indicator['name']
        window = indicator.get('window', None)
        
        try:
            if name == 'bb':
                bb = BollingerBands(close=df['close'], window=window)
                df[f'bb_upper_{window}'] = bb.bollinger_hband()
                df[f'bb_middle_{window}'] = bb.bollinger_mavg()
                df[f'bb_lower_{window}'] = bb.bollinger_lband()
                
            elif name == 'ma':
                ma = SMAIndicator(close=df['close'], window=window)
                df[f'ma_{window}'] = ma.sma_indicator()
                
            elif name == 'ema':
                ema = EMAIndicator(close=df['close'], window=window)
                df[f'ema_{window}'] = ema.ema_indicator()
                
            elif name == 'rsi':
                rsi = RSIIndicator(close=df['close'], window=window)
                df[f'rsi_{window}'] = rsi.rsi()
                
            elif name == 'macd':
                macd = MACD(close=df['close'], window_slow=window, window_fast=12, window_sign=9)
                df[f'macd_{window}'] = macd.macd()
                df[f'macd_signal_{window}'] = macd.macd_signal()
                df[f'macd_hist_{window}'] = macd.macd_diff()
                
            elif name == 'atr':
                atr = AverageTrueRange(high=df['high'], low=df['low'], close=df['close'], window=window)
                df[f'atr_{window}'] = atr.average_true_range()
                
            elif name == 'cci':
                cci = CCIIndicator(high=df['high'], low=df['low'], close=df['close'], window=window)
                df[f'cci_{window}'] = cci.cci()
                
            elif name == 'stochastic':
                stoch = StochasticOscillator(high=df['high'], low=df['low'], close=df['close'], window=window)
                df[f'stoch_k_{window}'] = stoch.stoch()
                df[f'stoch_d_{window}'] = stoch.stoch_signal()
                
            elif name == 'obv':
                obv = OnBalanceVolumeIndicator(close=df['close'], volume=df['volume'])
                df['obv'] = obv.on_balance_volume()
                
            elif name == 'mfi':
                mfi = MFIIndicator(high=df['high'], low=df['low'], close=df['close'], volume=df['volume'], window=window)
                df[f'mfi_{window}'] = mfi.money_flow_index()
        except Exception as e:
            raise Exception(f"Error calculating {name} indicator: {str(e)}")
    
    return df

## Indicators List

In [45]:
# Convert the column name to lower case
spx_df.columns = spx_df.columns.str.lower()

# INDICATORS = [
#         {'name': 'bb', 'window': 20},
#         {'name': 'ma', 'window': 20},
#         {'name': 'ema', 'window': 20},
#         {'name': 'rsi', 'window': 14},
#         {'name': 'macd', 'window': 26},  # MACD slow window
#         {'name': 'atr', 'window': 14},
#         {'name': 'cci', 'window': 20},
#         {'name': 'stochastic', 'window': 14},
#         {'name': 'obv'},
#         {'name': 'mfi', 'window': 14}
#     ]
INDICATORS = [
    {'name': 'bb', 'window': 20},          # Bollinger Bands
    {'name': 'ma', 'window': 50},          # Simple Moving Average
    {'name': 'ema', 'window': 12},         # Exponential Moving Average
    {'name': 'rsi', 'window': 14},         # Relative Strength Index
    {'name': 'macd', 'window': 26},        # MACD slow window (fast=12, signal=9)
    {'name': 'atr', 'window': 14},         # Average True Range
    {'name': 'cci', 'window': 20},         # Commodity Channel Index
    {'name': 'stochastic', 'window': 14},  # Stochastic oscillator (%K)
    {'name': 'adx', 'window': 14},         # Average Directional Index
    {'name': 'vortex', 'window': 14},      # Vortex Indicator
    {'name': 'obv'},                       # On-Balance Volume
    {'name': 'mfi', 'window': 14},         # Money Flow Index
    {'name': 'vwap'}                       # Volume-Weighted Average Price
]
# INDICATORS = [
#     {'name': 'ema',        'window': 5},    # fast EMA for very short-term momentum :contentReference[oaicite:0]{index=0}
#     {'name': 'roc',        'window': 5},    # 5-period Rate of Change for quick swings
#     {'name': 'rsi',        'window': 14},   # Relative Strength Index for short-term momentum :contentReference[oaicite:1]{index=1}
#     {'name': 'stochastic', 'window': 14},   # Stochastic oscillator (%K) :contentReference[oaicite:2]{index=2}
#     {'name': 'atr',        'window': 14},   # Average True Range for short-term volatility :contentReference[oaicite:3]{index=3}
#     {'name': 'ma',         'window': 20},   # 20-period SMA for mid-term trend
#     {'name': 'bb',         'window': 20},   # 20-period Bollinger Bands :contentReference[oaicite:4]{index=4}
#     {'name': 'macd',       'window': 26},   # MACD slow window (fast=12, signal=9) :contentReference[oaicite:5]{index=5}
#     {'name': 'adx',        'window': 14},   # Average Directional Index for trend strength :contentReference[oaicite:6]{index=6}
#     {'name': 'mfi',        'window': 14},   # Money Flow Index for volume-price interplay :contentReference[oaicite:7]{index=7}
#     {'name': 'vortex',     'window': 14},   # Vortex Indicator for trend confirmation
#     {'name': 'ma',         'window': 50},   # 50-period SMA for longer-term trend
#     {'name': 'ema',        'window': 50},   # 50-period EMA :contentReference[oaicite:8]{index=8}
#     {'name': 'ma',         'window': 200},  # 200-period SMA for very long-term trend :contentReference[oaicite:9]{index=9}
#     {'name': 'cci',        'window': 50},   # Commodity Channel Index for cyclical deviations
#     {'name': 'obv'},                       # On-Balance Volume (cumulative) for volume confirmation
#     {'name': 'vwap'}                       # Volume-Weighted Average Price for intraday anchoring
# ]

# spx_df = calculate_technical_indicators(spx_df, INDICATORS)

# DC Indicator

In [46]:
import pandas as pd
import numpy as np

def compute_atr(high: pd.Series, low: pd.Series, close: pd.Series, window: int = 10) -> pd.Series:
    """Calculate the rolling Average True Range (ATR)."""
    tr1 = high - low
    tr2 = (high - close.shift(1)).abs()
    tr3 = (low  - close.shift(1)).abs()
    tr = pd.concat([tr1, tr2, tr3], axis=1).max(axis=1)
    return tr.rolling(window).mean()


def detect_atr_dc_events(df: pd.DataFrame, atr_window: int = 10, k: float = 1.5) -> pd.DataFrame:
    """
    Detect ATR-based directional-change events.
    Returns a DataFrame with columns:
      'event_date', 'event_type', 'event_price', 'threshold', 'atr'
    """
    atr = compute_atr(df['high'], df['low'], df['close'], atr_window)
    mode = None
    last_extremum_price = df['close'].iloc[0]
    events = []

    for i in range(1, len(df)):
        date = df.index[i]
        price = df['close'].iloc[i]
        thresh = k * atr.iloc[i]

        if mode in (None, 'down') and price >= last_extremum_price + thresh:
            mode = 'up'
            last_extremum_price = price
            events.append((date, 'up', price, thresh, atr.iloc[i]))
        elif mode in (None, 'up') and price <= last_extremum_price - thresh:
            mode = 'down'
            last_extremum_price = price
            events.append((date, 'down', price, thresh, atr.iloc[i]))
        else:
            # update extremum within trend
            if mode == 'up':
                last_extremum_price = max(last_extremum_price, price)
            elif mode == 'down':
                last_extremum_price = min(last_extremum_price, price)

    return pd.DataFrame(events, columns=['event_date', 'event_type', 'event_price', 'threshold', 'atr'])


def add_event_features(price_df: pd.DataFrame,
                       atr_window: int = 10,
                       k: float = 1.5,
                       rv_window: int = 10,
                       momentum_window: int = 5,
                       vol_ma_window: int = 5) -> pd.DataFrame:
    """
    Augment price_df with event-based and contextual features:
      - overshoot_ratio
      - time_since_last_dc
      - return_since_last_dc
      - atr_at_event
      - realized_volatility
      - momentum
      - volume_spike_ratio
    """
    df = price_df.copy()
    df.set_index('date', inplace=True)

    # 1) Detect events
    events = detect_atr_dc_events(df, atr_window, k)

    # 2) Compute overshoot for each event
    overshoots = []
    for idx in range(len(events)-1):
        start = events.loc[idx, 'event_date']
        end = events.loc[idx+1, 'event_date']
        window = df.loc[start:end]
        if events.loc[idx, 'event_type'] == 'up':
            extremum = window['high'].max()
            overshoot = (extremum - events.loc[idx, 'event_price']) / events.loc[idx, 'threshold']
        else:
            extremum = window['low'].min()
            overshoot = (events.loc[idx, 'event_price'] - extremum) / events.loc[idx, 'threshold']
        overshoots.append(overshoot)
    overshoots.append(np.nan)  # no overshoot for last event
    events['overshoot_ratio'] = overshoots

    # 3) Compute time and return since last DC
    events['time_since_last_dc'] = (events['event_date'] - events['event_date'].shift(1)).dt.days
    events['return_since_last_dc'] = events['event_price'].pct_change()

    # 4) Map event features back to daily DataFrame
    for feat in ['overshoot_ratio', 'time_since_last_dc', 'return_since_last_dc', 'atr']:
        df[feat] = events.set_index('event_date')[feat].reindex(df.index, method='ffill')

    # 5) Realized volatility: rolling std of daily returns
    df['realized_volatility'] = df['close'].pct_change().rolling(rv_window).std()

    # 6) Momentum: price difference over window
    df['momentum'] = df['close'] - df['close'].shift(momentum_window)

    # 7) Volume spike ratio
    df['vol_ma'] = df['volume'].rolling(vol_ma_window).mean()
    df['volume_spike_ratio'] = df['volume'] / df['vol_ma']

    # clean up helper column
    df.drop(columns=['vol_ma'], inplace=True)

    df.reset_index(inplace=True)
    return df

In [47]:
# # Convert to UTC
# spx_df['date'] = pd.to_datetime(spx_df['date'], utc=True)
# spx_df['date'] = spx_df['date'].dt.tz_convert('UTC')

# spx_df = add_event_features(spx_df, atr_window=10, k=2.0)
# spx_df.head()

# # Sort news dataframe by date
# news_df = news_df.sort_values('date')

# # No need to convert timezone since it's already in US/Eastern
# # Just ensure it's datetime
# news_df['date'] = pd.to_datetime(news_df['date'], utc=True)

# Aggreate Data

## Event List

In [48]:
EVENT_TYPES = [
    "earnings", "merger", "dividend", "guidance", "regulatory",
    "macroeconomic", "monetary", "CEO change", "product launch",
    "supply-chain", "credit", "scandal", "analyst", "sector-wide",
    "geopolitical", "other"
]

## Aggreate by rolling window

In [49]:
import pandas as pd
import numpy as np

def aggregate_news_rolling(
    news_df: pd.DataFrame,
    price_df: pd.DataFrame,
    event_types: list,
    n_days: int = 3,
    half_life_days: float = 1.5
):
    """
    For each trading day, aggregate news from the previous n_days (including the current day).
    Args:
        news_df: DataFrame with ['date', 'relevance_score', 'event_importance', 'event_type', 'sentiment_score_llm']
        price_df: DataFrame with ['date', 'close', 'volume']
        event_types: List of all possible event types
        n_days: Number of days in the rolling window
        half_life_days: Half-life for exponential decay (in days)
    Returns:
        pd.DataFrame: Aggregated data with one-hot encoded event types and price data
    """
    # Ensure datetime
    news_df = news_df.copy()
    price_df = price_df.copy()
    news_df['date'] = pd.to_datetime(news_df['date'], utc=True)
    price_df['date'] = pd.to_datetime(price_df['date'], utc=True)

    # Prepare price data - convert dates to 4 PM ET trading days
    price_df['trading_day'] = price_df['date'].apply(
        lambda x: pd.Timestamp(
            year=x.year,
            month=x.month,
            day=x.day,
            hour=16,
            minute=0,
            second=0,
            tz='US/Eastern'
        )
    )

    # Prepare output list
    agg_list = []

    for trading_day in price_df['trading_day']:
        # Define window: n_days before (inclusive)
        window_start = trading_day - pd.Timedelta(days=n_days-1)
        window_end = trading_day

        # Select news in the window
        mask = (news_df['date'] >= window_start) & (news_df['date'] <= window_end)
        news_window = news_df.loc[mask].copy()

        # Compute decay factor for each news item (relative to trading day)
        lam = np.log(2) / half_life_days
        delta = (trading_day - news_window['date']).dt.total_seconds() / (24*3600)
        delta = np.clip(delta, 0, None)
        news_window['decay'] = np.exp(-lam * delta)

        # Calculate weighted sentiment score
        news_window['weighted_sentiment_llm'] = (
            news_window['sentiment_score_llm'] *
            news_window['relevance_score'] *
            news_window['event_importance'] *
            news_window['decay']
        )

        # One-hot encode event_type
        news_window['event_type'] = pd.Categorical(news_window['event_type'], categories=event_types)
        dummies = pd.get_dummies(news_window['event_type']).reindex(columns=event_types, fill_value=0)
        weighted_dummies = dummies.mul(news_window['weighted_sentiment_llm'], axis=0)

        # Aggregate by sum for this trading day
        agg_row = weighted_dummies.sum(axis=0)
        agg_row['trading_day'] = trading_day

        agg_list.append(agg_row)

    # Combine all rows
    news_agg = pd.DataFrame(agg_list).fillna(0.0)

    # Merge with price data
    merged_df = pd.merge(
        price_df,
        news_agg,
        on='trading_day',
        how='left'
    ).fillna(0.0)

    # Sort by trading day
    merged_df = merged_df.sort_values('trading_day').reset_index(drop=True)

    return merged_df

In [36]:
spx_df = calculate_technical_indicators(spx_df, INDICATORS)
aggregated_df = aggregate_news_rolling(
    news_df=news_df,
    price_df=spx_df,
    event_types=EVENT_TYPES,
    n_days=3,                # Use a 3-day rolling window
    half_life_days=2,
)

display(aggregated_df.head())
aggregated_df

,date,open,high,low,close,volume,bb_upper_20,bb_middle_20,bb_lower_20,ma_50,...,monetary,CEO change,product launch,supply-chain,credit,scandal,analyst,sector-wide,geopolitical,other
0,2006-10-20 04:00:00+00:00,1366.939941,1368.660034,1362.099976,1368.599976,2526410000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2006-10-23 04:00:00+00:00,1368.579956,1377.400024,1363.939941,1377.020020,2480430000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2006-10-24 04:00:00+00:00,1377.020020,1377.780029,1372.420044,1377.380005,2876890000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2006-10-25 04:00:00+00:00,1377.359985,1383.609985,1376.000000,1382.219971,2953540000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2006-10-26 04:00:00+00:00,1382.209961,1389.449951,1379.469971,1389.079956,2793350000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

,date,open,high,low,close,volume,bb_upper_20,bb_middle_20,bb_lower_20,ma_50,...,monetary,CEO change,product launch,supply-chain,credit,scandal,analyst,sector-wide,geopolitical,other
0,2006-10-20 04:00:00+00:00,1366.939941,1368.660034,1362.099976,1368.599976,2526410000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000
1,2006-10-23 04:00:00+00:00,1368.579956,1377.400024,1363.939941,1377.020020,2480430000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000
2,2006-10-24 04:00:00+00:00,1377.020020,1377.780029,1372.420044,1377.380005,2876890000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000
3,2006-10-25 04:00:00+00:00,1377.359985,1383.609985,1376.000000,1382.219971,2953540000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000
4,2006-10-26 04:00:00+00:00,1382.209961,1389.449951,1379.469971,1389.079956,2793350000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1782,2013-11-19 05:00:00+00:00,1790.790039,1795.510010,1784.719971,1787.869995,3224450000,1797.639304,1769.135004,1740.630704,1728.317009,...,0.275309,0.0,0.003009,0.005004,0.0,0.0,0.0,0.029177,-0.412655,0.012696
1783,2013-11-20 05:00:00+00:00,1789.589966,1795.729980,1777.229980,1781.369995,3109140000,1797.840637,1770.884503,1743.928370,1730.161809,...,0.066378,0.0,0.001199,0.003539,0.0,0.0,0.0,0.017806,-0.314594,-0.022605
1784,2013-11-21 05:00:00+00:00,1783.520020,1797.160034,1783.520020,1795.849976,3256630000,1800.665599,1773.073505,1745.481410,1732.410408,...,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000
1785,2013-11-22 05:00:00+00:00,1797.209961,1804.839966,1794.699951,1804.760010,3055140000,1805.431027,1775.323004,1745.214981,1734.745808,...,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000
1786,2013-11-25 05:00:00+00:00,1806.329956,1808.099976,1800.579956,1802.479980,2998540000,1809.008193,1777.341504,1745.674815,1736.843408,...,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000

# Save csv

In [15]:
aggregated_df.to_csv('aggregated_data.csv', index=False)

# Model Training

## Training Pipeline

### Import Library

In [16]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D, LSTM, Dense, Dropout, Input
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping
import optuna
from sklearn.preprocessing import MinMaxScaler
import matplotlib.pyplot as plt
from typing import Callable, Dict, Any, Tuple
from sklearn.metrics import mean_squared_error, f1_score


def create_sequences(data, seq_length, target_col_idx):
    """Create sequences for time series data."""
    X, y = [], []
    for i in range(len(data) - seq_length):
        X.append(data[i:(i + seq_length)])
        y.append(data[i + seq_length, target_col_idx])
    return np.array(X), np.array(y)

def prepare_data_for_model(df: pd.DataFrame, seq_length: int, test_size: float = 0.2) -> Tuple:
    """Prepare data for the model, handling datetime columns properly."""
    # Create a copy of the dataframe
    df = df.copy()
    
    # Store the datetime column separately
    datetime_col = df['date']
    
    # Get numeric columns (excluding datetime)
    numeric_cols = df.select_dtypes(include=[np.number]).columns
    df_numeric = df[numeric_cols]
    
    # Scale the numeric data
    scaler = MinMaxScaler()
    scaled_data = scaler.fit_transform(df_numeric)
    
    # Find the index of the 'close' column
    close_col_idx = list(numeric_cols).index('close')
    
    # Create sequences
    X, y = create_sequences(scaled_data, seq_length, close_col_idx)
    
    # Split into train and test sets
    train_size = int(len(X) * (1 - test_size))
    X_train, X_test = X[:train_size], X[train_size:]
    y_train, y_test = y[:train_size], y[train_size:]
    
    # Get corresponding dates for test set
    test_dates = datetime_col[train_size + seq_length:].values
    
    return X_train, X_test, y_train, y_test, scaler, test_dates, numeric_cols

/Users/jasonlam/miniconda3/envs/data_pre/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

### LSTM+CNN

In [17]:
def build_cnn_lstm_model(trial, seq_length, n_features):
    """CNN+LSTM model with variable number of LSTM layers."""

    # CNN parameters
    cnn_filters = trial.suggest_int('cnn_filters', 32, 128)
    cnn_kernel = trial.suggest_int('cnn_kernel', 2, 5)
    cnn_dropout = trial.suggest_float('cnn_dropout', 0.1, 0.5)
    
    # LSTM parameters
    lstm_layers = trial.suggest_int('lstm_layers', 2, 5)  # Let Optuna choose 1, 2, or 3 layers
    lstm_units = trial.suggest_int('lstm_units', 32, 128)
    lstm_dropout = trial.suggest_float('lstm_dropout', 0.1, 0.5)
    
    # Learning rate
    learning_rate = trial.suggest_float('learning_rate', 1e-5, 1e-2, log=True)
    
    model = Sequential()
    model.add(Input(shape=(seq_length, n_features)))
    model.add(Conv1D(filters=cnn_filters, kernel_size=cnn_kernel, activation='relu'))
    model.add(MaxPooling1D(pool_size=2))
    model.add(Dropout(cnn_dropout))
    
    # Add LSTM layers dynamically
    for i in range(lstm_layers):
        # Only the last LSTM layer should not return sequences
        return_seq = (i < lstm_layers - 1)
        model.add(LSTM(lstm_units, return_sequences=return_seq))
        model.add(Dropout(lstm_dropout))
    
    model.add(Dense(1))
    model.compile(optimizer=Adam(learning_rate=learning_rate), loss='mse')
    return model

### LSTM

In [18]:
def build_lstm_model(trial, seq_length, n_features, **kwargs):
    """LSTM model with variable number of LSTM layers."""

    # Hyperparameters from best trial
    lstm_layers = 5
    lstm_units = 67
    dropout_rate = 0.1294676223336333
    learning_rate = 0.005698251072263444

    model = Sequential()
    model.add(Input(shape=(seq_length, n_features)))

    # Add LSTM layers dynamically
    for i in range(lstm_layers):
        return_seq = (i < lstm_layers - 1)
        units = lstm_units if i == 0 else lstm_units // 2  # Optional: halve units for deeper layers
        model.add(LSTM(units, return_sequences=return_seq))
        model.add(Dropout(dropout_rate))

    model.add(Dense(32, activation='relu'))
    model.add(Dense(1))

    model.compile(optimizer=Adam(learning_rate=learning_rate), loss='mse')
    return model

### Train and Evaluate

In [19]:
from typing import Union

def train_and_evaluate_model(
    news_df: pd.DataFrame,
    price_df: pd.DataFrame,
    event_types: list,
    seq_length: int,
    n_trials: int = 20,
    build_model_fn: Callable = build_lstm_model,
    model_params: Dict[str, Any] = None,
    half_life_range: Union[tuple, float] = (0.5, 10.0),
    n_days_range: Union[tuple, int] = (1, 10)
) -> Tuple:
    """
    Train and evaluate the model with hyperparameter optimization, including half_life_days as a hyperparameter.

    Args:
        news_df: Raw news DataFrame
        price_df: Raw price DataFrame
        event_types: List of event types for one-hot encoding
        seq_length: Length of input sequences
        n_trials: Number of Optuna trials
        build_model_fn: Model building function
        model_params: Additional model parameters
        half_life_range: (min, max) range for half_life_days

    Returns:
        Tuple containing (model, history, predictions, actual, test_dates, best_params)
    """

    def objective(trial):
        # 1. Get half_life_days and n_days for this trial
        half_life_days = half_life_range if isinstance(half_life_range, float) else trial.suggest_float('half_life_days', half_life_range[0], half_life_range[1])
        n_days = n_days_range if isinstance(n_days_range, int) else trial.suggest_int('n_days', n_days_range[0], n_days_range[1])

        # 2. Aggregate data using the suggested half_life_days
        aggregated_df = aggregate_news_rolling(
        news_df=news_df,
        price_df=spx_df,
        event_types=EVENT_TYPES,
        n_days=n_days,                
        half_life_days=half_life_days
        )

        # 3. Prepare data for the model
        X_train, X_test, y_train, y_test, scaler, test_dates, numeric_cols = prepare_data_for_model(
            aggregated_df, seq_length=seq_length
        )

        # 4. Split training data into train and validation sets
        val_size = int(len(X_train) * 0.2)
        X_train_final, X_val = X_train[:-val_size], X_train[-val_size:]
        y_train_final, y_val = y_train[:-val_size], y_train[-val_size:]

        # 5. Build and train the model
        model = build_model_fn(trial, seq_length, X_train.shape[2], **(model_params or {}))
        early_stopping = tf.keras.callbacks.EarlyStopping(
            monitor='val_loss',
            patience=10,
            restore_best_weights=True
        )
        history = model.fit(
            X_train_final, y_train_final,
            validation_data=(X_val, y_val),
            epochs=100,
            batch_size=32,
            callbacks=[early_stopping],
            verbose=0
        )

        # 6. Return the best validation loss
        return min(history.history['val_loss'])

    # 7. Run Optuna optimization
    study = optuna.create_study(direction='minimize')
    study.optimize(objective, n_trials=n_trials)

    # 8. After finding the best trial, rebuild the dataset with the best half_life_days
    best_half_life = study.best_params.get('half_life_days', half_life_range if isinstance(half_life_range, float) else half_life_range[0])
    n_days = study.best_params.get('n_days', n_days_range if isinstance(n_days_range, int) else n_days_range[0])
    best_aggregated_df = aggregate_news_rolling(
        news_df, price_df, event_types, half_life_days=best_half_life, n_days=n_days
    )

    # 9. Prepare data for the final model
    X_train, X_test, y_train, y_test, scaler, test_dates, numeric_cols = prepare_data_for_model(
        best_aggregated_df, seq_length=seq_length
    )

    # 10. Train the final model with the best hyperparameters
    best_model = build_model_fn(study.best_trial, seq_length, X_train.shape[2], **(model_params or {}))
    early_stopping = tf.keras.callbacks.EarlyStopping(
        monitor='val_loss',
        patience=10,
        restore_best_weights=True
    )
    history = best_model.fit(
        X_train, y_train,
        validation_split=0.2,
        epochs=100,
        batch_size=32,
        callbacks=[early_stopping],
        verbose=1
    )

    # 11. Make predictions
    predictions = best_model.predict(X_test)
    close_col_idx = list(numeric_cols).index('close')
    pred_reshaped = np.zeros((len(predictions), len(numeric_cols)))
    pred_reshaped[:, close_col_idx] = predictions.flatten()
    predictions = scaler.inverse_transform(pred_reshaped)[:, close_col_idx]
    actual_reshaped = np.zeros((len(y_test), len(numeric_cols)))
    actual_reshaped[:, close_col_idx] = y_test
    actual = scaler.inverse_transform(actual_reshaped)[:, close_col_idx]

    # 11. Print the best hyperparameters found
    print("Best hyperparameters found:")
    for k, v in study.best_params.items():
        print(f"{k}: {v}")
    print(f"seq_length: {seq_length}")

    return best_model, history, predictions, actual, test_dates, study.best_params

### Plot Results

In [20]:
def plot_results(predictions1, predictions2, actual, test_dates, history, model1_name="Model 1", model2_name="Model 2"):
    """Plot the results and training history."""
    # Create figure with two subplots
    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(15, 10))
    
    # Plot predictions vs actual
    ax1.plot(test_dates, actual, label='Actual', color='blue')
    ax1.plot(test_dates, predictions1, label=model1_name, color='red')
    ax1.plot(test_dates, predictions2, label=model2_name, color='green')
    ax1.set_title('Actual vs Predicted Stock Prices')
    ax1.set_xlabel('Date')
    ax1.set_ylabel('Price')
    ax1.legend()
    ax1.grid(True)
    
    # Plot training history
    ax2.plot(history.history['loss'], label='Training Loss')
    ax2.plot(history.history['val_loss'], label='Validation Loss')
    ax2.set_title('Model Loss During Training')
    ax2.set_xlabel('Epoch')
    ax2.set_ylabel('Loss')
    ax2.legend()
    ax2.grid(True)
    
    # Calculate metrics for both models
    metrics = {
        'MSE': [],
        'Directional Accuracy': [],
        'F1 Score': []
    }
    
    for pred in [predictions1, predictions2]:
        # MSE
        mse = mean_squared_error(actual, pred)
        metrics['MSE'].append(mse)
        
        # Directional Accuracy
        actual_direction = np.sign(np.diff(actual))
        pred_direction = np.sign(np.diff(pred))
        directional_accuracy = np.mean(actual_direction == pred_direction)
        metrics['Directional Accuracy'].append(directional_accuracy)
        
        # F1 Score
        actual_binary = (actual_direction > 0).astype(int)
        pred_binary = (pred_direction > 0).astype(int)
        f1 = f1_score(actual_binary, pred_binary)
        metrics['F1 Score'].append(f1)
    
    # Create comparison table
    table_data = [
        ['Metric', model1_name, model2_name],
        ['MSE', f'{metrics["MSE"][0]:.4f}', f'{metrics["MSE"][1]:.4f}'],
        ['Directional Accuracy', f'{metrics["Directional Accuracy"][0]:.4f}', f'{metrics["Directional Accuracy"][1]:.4f}'],
        ['F1 Score', f'{metrics["F1 Score"][0]:.4f}', f'{metrics["F1 Score"][1]:.4f}']
    ]
    
    # Add table to plot
    table = ax1.table(cellText=table_data,
                     loc='upper right',
                     cellLoc='center',
                     colWidths=[0.2, 0.15, 0.15])
    table.auto_set_font_size(False)
    table.set_fontsize(9)
    table.scale(1.2, 1.5)
    
    plt.tight_layout()
    plt.show()

In [21]:
seq_length = 10
n_trials = 20

# Test different Model

## Balance Indicator Set

### Test LSTM + CNN

In [ ]:
best_model, history, LSTM_CNN_predictions, actual, test_dates, best_params = train_and_evaluate_model(
    news_df=news_df,
    price_df=spx_df,
    event_types=EVENT_TYPES,
    seq_length=seq_length,
    n_trials=n_trials,
    build_model_fn=build_cnn_lstm_model,  # or your custom model function
    model_params=None,                    # or pass a dict of extra model params if needed
    half_life_range=(0.5, 10.0),           # or any range you want to search
    n_days_range=(1, 10)
)

# Save the model to a file (e.g., HDF5 format)
best_model.save('LSTM_CNN_Model.keras')

[I 2025-05-27 18:12:23,539] A new study created in memory with name: no-name-05e2a2b1-ca2d-4ab0-bb39-51e73e120173
[I 2025-05-27 18:12:33,596] Trial 0 finished with value: 0.0018302456010133028 and parameters: {'half_life_days': 6.206690118924735, 'n_days': 2, 'cnn_filters': 99, 'cnn_kernel': 4, 'cnn_dropout': 0.23827128056292604, 'lstm_layers': 2, 'lstm_units': 71, 'lstm_dropout': 0.17731470302301694, 'learning_rate': 3.391606629816898e-05}. Best is trial 0 with value: 0.0018302456010133028.
[W 2025-05-27 18:12:35,850] Trial 1 failed with parameters: {'half_life_days': 2.4284501530282254, 'n_days': 3} because of the following error: KeyboardInterrupt().
Traceback (most recent call last):
  File "/Users/jasonlam/miniconda3/envs/data_pre/lib/python3.12/site-packages/optuna/study/_optimize.py", line 197, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "/var/folders/s2/gqpw_6dd5n7b8c1hzy_q5s0w0000gn/T/ipykernel_11981/343165691.py", line 37, in objective
    aggregated_df = aggregate_news_rolling(
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/folders/s2/gqpw_6dd5n7b8c1hzy_q5s0w0000gn/T/ipykernel_11981/894694629.py", line 55, in aggregate_news_rolling
    delta = (trading_day - news_window['date']).dt.total_seconds() / (24*3600)
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~
  File "/Users/jasonlam/miniconda3/envs/data_pre/lib/python3.12/site-packages/pandas/core/ops/common.py", line 76, in new_method
    return method(self, other)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/jasonlam/miniconda3/envs/data_pre/lib/python3.12/site-packages/pandas/core/arraylike.py", line 210, in __truediv__
    return self._arith_method(other, operator.truediv)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jasonlam/miniconda3/envs/data_pre/lib/python3.12/site-packages/pandas/core/series.py", line 6135, in _arith_method
    return base.IndexOpsMixin._arith_method(self, other, op)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jasonlam/miniconda3/envs/data_pre/lib/python3.12/site-packages/pandas/core/base.py", line 1384, in _arith_method
    return self._construct_result(result, name=res_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jasonlam/miniconda3/envs/data_pre/lib/python3.12/site-packages/pandas/core/series.py", line 6231, in _construct_result
    out = self._constructor(result, index=self.index, dtype=dtype, copy=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jasonlam/miniconda3/envs/data_pre/lib/python3.12/site-packages/pandas/core/series.py", line 584, in __init__
    data = sanitize_array(data, index, dtype, copy)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jasonlam/miniconda3/envs/data_pre/lib/python3.12/site-packages/pandas/core/construction.py", line 664, in sanitize_array
    subarr = _sanitize_str_dtypes(subarr, data, dtype, copy)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jasonlam/miniconda3/envs/data_pre/lib/python3.12/site-packages/pandas/core/construction.py", line 744, in _sanitize_str_dtypes
    if issubclass(result.dtype.type, str):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
[W 2025-05-27 18:12:35,855] Trial 1 failed with value None.

KeyboardInterrupt:

### Test LSTM

In [ ]:
best_model, history, LSTM_predictions, actual, test_dates, best_params = train_and_evaluate_model(
    news_df=news_df,
    price_df=spx_df,
    event_types=EVENT_TYPES,
    seq_length=seq_length,
    n_trials=n_trials,
    build_model_fn=build_lstm_model,  # or your custom model function
    model_params=None,                    # or pass a dict of extra model params if needed
    half_life_range=(0.5, 10.0),           # or any range you want to search
    n_days_range=(1, 10)
)


# Save the model to a file (e.g., HDF5 format)
best_model.save('LSTM_Model.keras')